name: 'Build error-prop'
description: 'Build error-prop'
inputs:
  command:
    required: true
runs:
  using: 'docker'
  image: 'docker://ucdavisplse/mpi-error-prop-artifact'
  args:
    - 'test-error-prop'
